-- -------------------------------------------------------------
--  PAÍS
-- -------------------------------------------------------------

INSERT INTO pais (nombre) VALUES
    ('Guatemala');


-- -------------------------------------------------------------
--  DEPARTAMENTOS
-- -------------------------------------------------------------

INSERT INTO departamento (pais_id, nombre) VALUES
    (1, 'Guatemala'),
    (1, 'El Progreso'),
    (1, 'Sacatepéquez'),
    (1, 'Chimaltenango'),
    (1, 'Escuintla'),
    (1, 'Santa Rosa'),
    (1, 'Sololá'),
    (1, 'Totonicapán'),
    (1, 'Quetzaltenango'),
    (1, 'Suchitepéquez'),
    (1, 'Retalhuleu'),
    (1, 'San Marcos'),
    (1, 'Huehuetenango'),
    (1, 'Quiché'),
    (1, 'Baja Verapaz'),
    (1, 'Alta Verapaz'),
    (1, 'Petén'),
    (1, 'Izabal'),
    (1, 'Zacapa'),
    (1, 'Chiquimula'),
    (1, 'Jalapa'),
    (1, 'Jutiapa');


-- -------------------------------------------------------------
--  MUNICIPIO
-- -------------------------------------------------------------

INSERT INTO municipio (departamento_id, nombre) VALUES
    (1,'Guatemala'),
    (1,'Santa Catarina Pinula'),
    (1,'San José Pinula'),
    (1,'San José del Golfo'),
    (1,'Palencia'),
    (1,'Chinautla'),
    (1,'San Pedro Ayampuc'),
    (1,'Mixco'),
    (1,'San Pedro Sacatepéquez'),
    (1,'San Juan Sacatepéquez'),
    (1,'San Raymundo'),
    (1,'Chuarrancho'),
    (1,'Fraijanes'),
    (1,'Amatitlán'),
    (1,'Villa Nueva'),
    (1,'Villa Canales'),
    (1,'San Miguel Petapa'),

    (2,'Guastatoya'),
    (2,'Morazán'),
    (2,'San Agustín Acasaguastlán'),
    (2,'San Cristóbal Acasaguastlán'),
    (2,'El Jícaro'),
    (2,'Sansare'),
    (2,'Sanarate'),
    (2,'San Antonio La Paz'),

    (3,'Antigua Guatemala'),
    (3,'Jocotenango'),
    (3,'Pastores'),
    (3,'Sumpango'),
    (3,'Santo Domingo Xenacoj'),
    (3,'Santiago Sacatepéquez'),
    (3,'San Bartolomé Milpas Altas'),
    (3,'San Lucas Sacatepéquez'),
    (3,'Santa Lucía Milpas Altas'),
    (3,'Magdalena Milpas Altas'),
    (3,'Santa María de Jesús'),
    (3,'Ciudad Vieja'),
    (3,'San Miguel Dueñas'),
    (3,'Alotenango'),
    (3,'San Antonio Aguas Calientes'),
    (3,'Santa Catarina Barahona'),

    (4,'Chimaltenango'),
    (4,'San José Poaquil'),
    (4,'San Martín Jilotepeque'),
    (4,'San Juan Comalapa'),
    (4,'Santa Apolonia'),
    (4,'Tecpán Guatemala'),
    (4,'Patzún'),
    (4,'Pochuta'),
    (4,'Patzicía'),
    (4,'Santa Cruz Balanyá'),
    (4,'Acatenango'),
    (4,'Yepocapa'),
    (4,'San Andrés Itzapa'),
    (4,'Parramos'),
    (4,'Zaragoza'),
    (4,'El Tejar'),

    (5,'Escuintla'),
    (5,'Santa Lucía Cotzumalguapa'),
    (5,'La Democracia'),
    (5,'Siquinalá'),
    (5,'Masagua'),
    (5,'Tiquisate'),
    (5,'La Gomera'),
    (5,'Guanagazapa'),
    (5,'San José'),
    (5,'Iztapa'),
    (5,'Palín'),
    (5,'San Vicente Pacaya'),
    (5,'Nueva Concepción'),

    (6,'Cuilapa'),
    (6,'Barberena'),
    (6,'Santa Rosa de Lima'),
    (6,'Casillas'),
    (6,'San Rafael Las Flores'),
    (6,'Oratorio'),
    (6,'San Juan Tecuaco'),
    (6,'Chiquimulilla'),
    (6,'Taxisco'),
    (6,'Santa María Ixhuatán'),
    (6,'Guazacapán'),
    (6,'Santa Cruz Naranjo'),
    (6,'Pueblo Nuevo Viñas'),
    (6,'Nueva Santa Rosa'),

    (7,'Sololá'),
    (7,'San José Chacayá'),
    (7,'Santa María Visitación'),
    (7,'Santa Lucía Utatlán'),
    (7,'Nahualá'),
    (7,'Santa Catarina Ixtahuacán'),
    (7,'Santa Clara La Laguna'),
    (7,'Concepción'),
    (7,'San Andrés Semetabaj'),
    (7,'Panajachel'),
    (7,'Santa Catarina Palopó'),
    (7,'San Antonio Palopó'),
    (7,'San Lucas Tolimán'),
    (7,'Santa Cruz La Laguna'),
    (7,'San Pablo La Laguna'),
    (7,'San Marcos La Laguna'),
    (7,'San Juan La Laguna'),
    (7,'San Pedro La Laguna'),
    (7,'Santiago Atitlán'),

    (8,'Totonicapán'),
    (8,'San Cristóbal Totonicapán'),
    (8,'San Francisco El Alto'),
    (8,'San Andrés Xecul'),
    (8,'Momostenango'),
    (8,'Santa María Chiquimula'),
    (8,'Santa Lucía La Reforma'),
    (8,'San Bartolo'),

    (9,'Quetzaltenango'),
    (9,'Salcajá'),
    (9,'Olintepeque'),
    (9,'San Carlos Sija'),
    (9,'Sibilia'),
    (9,'Cabricán'),
    (9,'Cajolá'),
    (9,'San Miguel Sigüilá'),
    (9,'San Juan Ostuncalco'),
    (9,'San Mateo'),
    (9,'Concepción Chiquirichapa'),
    (9,'San Martín Sacatepéquez'),
    (9,'Almolonga'),
    (9,'Cantel'),
    (9,'Huitán'),
    (9,'Zunil'),
    (9,'Colomba'),
    (9,'San Francisco La Unión'),
    (9,'El Palmar'),
    (9,'Coatepeque'),
    (9,'Génova'),
    (9,'Flores Costa Cuca'),
    (9,'La Esperanza'),
    (9,'Palestina de Los Altos'),

    (10,'Mazatenango'),
    (10,'Cuyotenango'),
    (10,'San Francisco Zapotitlán'),
    (10,'San Bernardino'),
    (10,'San José El Ídolo'),
    (10,'Santo Domingo Suchitepéquez'),
    (10,'San Lorenzo'),
    (10,'Samayac'),
    (10,'San Pablo Jocopilas'),
    (10,'San Antonio Suchitepéquez'),
    (10,'San Miguel Panán'),
    (10,'San Gabriel'),
    (10,'Chicacao'),
    (10,'Patulul'),
    (10,'Santa Bárbara'),
    (10,'San Juan Bautista'),
    (10,'Santo Tomás La Unión'),
    (10,'Zunilito'),
    (10,'Pueblo Nuevo'),
    (10,'Río Bravo'),

    (11,'Retalhuleu'),
    (11,'San Sebastián'),
    (11,'Santa Cruz Muluá'),
    (11,'San Martín Zapotitlán'),
    (11,'San Felipe'),
    (11,'San Andrés Villa Seca'),
    (11,'Champerico'),
    (11,'Nuevo San Carlos'),
    (11,'El Asintal'),

    (12,'San Marcos'),
    (12,'San Pedro Sacatepéquez'),
    (12,'San Antonio Sacatepéquez'),
    (12,'Comitancillo'),
    (12,'San Miguel Ixtahuacán'),
    (12,'Concepción Tutuapa'),
    (12,'Tacaná'),
    (12,'Sibinal'),
    (12,'Tajumulco'),
    (12,'Tejutla'),
    (12,'San Rafael Pie de la Cuesta'),
    (12,'Nuevo Progreso'),
    (12,'El Tumbador'),
    (12,'San José El Rodeo'),
    (12,'Malacatán'),
    (12,'Catarina'),
    (12,'Ayutla'),
    (12,'Ocos'),
    (12,'San Pablo'),
    (12,'El Quetzal'),
    (12,'La Reforma'),
    (12,'Pajapita'),
    (12,'Ixchiguán'),
    (12,'San José Ojetenam'),
    (12,'San Cristóbal Cucho'),
    (12,'Sipacapa'),
    (12,'Esquipulas Palo Gordo'),
    (12,'Río Blanco'),
    (12,'San Lorenzo'),

    (13,'Huehuetenango'),
    (13,'Chiantla'),
    (13,'Malacatancito'),
    (13,'Cuilco'),
    (13,'Nentón'),
    (13,'San Pedro Necta'),
    (13,'Jacaltenango'),
    (13,'San Pedro Soloma'),
    (13,'San Ildefonso Ixtahuacán'),
    (13,'Santa Bárbara'),
    (13,'La Libertad'),
    (13,'La Democracia'),
    (13,'San Miguel Acatán'),
    (13,'San Rafael La Independencia'),
    (13,'Todos Santos Cuchumatán'),
    (13,'San Juan Atitán'),
    (13,'Santa Eulalia'),
    (13,'San Mateo Ixtatán'),
    (13,'Colotenango'),
    (13,'San Sebastián Huehuetenango'),
    (13,'Tectitán'),
    (13,'Concepción Huista'),
    (13,'San Juan Ixcoy'),
    (13,'San Antonio Huista'),
    (13,'San Sebastián Coatán'),
    (13,'Santa Cruz Barillas'),
    (13,'Aguacatán'),
    (13,'San Rafael Petzal'),
    (13,'San Gaspar Ixchil'),
    (13,'Santiago Chimaltenango'),
    (13,'Santa Ana Huista'),

    (14,'Santa Cruz del Quiché'),
    (14,'Chiché'),
    (14,'Chinique'),
    (14,'Zacualpa'),
    (14,'Chajul'),
    (14,'Santo Tomás Chichicastenango'),
    (14,'Patzité'),
    (14,'San Antonio Ilotenango'),
    (14,'San Pedro Jocopilas'),
    (14,'Cunén'),
    (14,'San Juan Cotzal'),
    (14,'Joyabaj'),
    (14,'Nebaj'),
    (14,'San Andrés Sajcabajá'),
    (14,'Uspantán'),
    (14,'Sacapulas'),
    (14,'San Bartolomé Jocotenango'),
    (14,'Canillá'),
    (14,'Chicamán'),

    (15,'Salamá'),
    (15,'San Miguel Chicaj'),
    (15,'Rabinal'),
    (15,'Cubulco'),
    (15,'Granados'),
    (15,'Santa Cruz El Chol'),
    (15,'San Jerónimo'),
    (15,'Purulhá'),

    (16,'Cobán'),
    (16,'Santa Cruz Verapaz'),
    (16,'San Cristóbal Verapaz'),
    (16,'Tactic'),
    (16,'Tamahú'),
    (16,'Tucurú'),
    (16,'Panzós'),
    (16,'Senahú'),
    (16,'San Pedro Carchá'),
    (16,'San Juan Chamelco'),
    (16,'Lanquín'),
    (16,'Cahabón'),
    (16,'Chisec'),
    (16,'Chahal'),
    (16,'Fray Bartolomé de las Casas'),
    (16,'Santa Catalina La Tinta'),
    (16,'Raxruhá'),

    (17,'Flores'),
    (17,'San José'),
    (17,'San Benito'),
    (17,'San Andrés'),
    (17,'La Libertad'),
    (17,'San Francisco'),
    (17,'Santa Ana'),
    (17,'Dolores'),
    (17,'San Luis'),
    (17,'Sayaxché'),
    (17,'Melchor de Mencos'),
    (17,'Poptún'),
    (17,'Las Cruces'),
    (17,'El Chal'),

    (18,'Puerto Barrios'),
    (18,'Livingston'),
    (18,'El Estor'),
    (18,'Morales'),
    (18,'Los Amates'),

    (19,'Zacapa'),
    (19,'Estanzuela'),
    (19,'Río Hondo'),
    (19,'Gualán'),
    (19,'Teculután'),
    (19,'Usumatlán'),
    (19,'Cabañas'),
    (19,'San Diego'),
    (19,'La Unión'),
    (19,'Huité'),

    (20,'Chiquimula'),
    (20,'San José La Arada'),
    (20,'San Juan Ermita'),
    (20,'Jocotán'),
    (20,'Camotán'),
    (20,'Olopa'),
    (20,'Esquipulas'),
    (20,'Concepción Las Minas'),
    (20,'Quetzaltepeque'),
    (20,'San Jacinto'),
    (20,'Ipala'),

    (21,'Jalapa'),
    (21,'San Pedro Pinula'),
    (21,'San Luis Jilotepeque'),
    (21,'San Manuel Chaparrón'),
    (21,'San Carlos Alzatate'),
    (21,'Monjas'),
    (21,'Mataquescuintla'),

    (22,'Jutiapa'),
    (22,'El Progreso'),
    (22,'Santa Catarina Mita'),
    (22,'Agua Blanca'),
    (22,'Asunción Mita'),
    (22,'Yupiltepeque'),
    (22,'Atescatempa'),
    (22,'Jerez'),
    (22,'El Adelanto'),
    (22,'Zapotitlán'),
    (22,'Comapa'),
    (22,'Jalpatagua'),
    (22,'Conguaco'),
    (22,'Moyuta'),
    (22,'Pasaco'),
    (22,'San José Acatempa'),
    (22,'Quesada');